<?php
namespace Ksfraser\Security\OAuth2\PKCE;

use Ksfraser\Security\Exceptions\TokenException;

/**
 * PKCE Handler - RFC 7636
 * 
 * Proof Key for Code Exchange (PKCE) protects authorization codes against
 * interception attacks, particularly important for mobile and single-page apps.
 * 
 * Components:
 * - code_verifier: Random string (43-128 chars) generated by client
 * - code_challenge: Either plain verifier or SHA256 hash of verifier
 * - code_challenge_method: "plain" or "S256"
 * 
 * Flow:
 * 1. Client generates random code_verifier
 * 2. Client creates code_challenge from verifier
 * 3. Client sends challenge to authorization endpoint
 * 4. Authorization server stores challenge with code
 * 5. Client exchanges code + verifier for token
 * 6. Server verifies: hash(verifier) === stored_challenge
 * 
 * Security:
 * - Even if authorization code is intercepted, attacker won't have verifier
 * - Server proves client didn't change code during transmission
 * - Mandatory for public clients (mobile apps, SPAs)
 * - Optional but recommended for confidential clients
 * 
 * @package   Ksfraser\Security\OAuth2\PKCE
 * @author    KSF Development Team
 * @version   1.0.0
 * @since     2026-04-03
 */
class PKCEHandler
{
    /**
     * Minimum code verifier length per RFC 7636
     */
    const VERIFIER_MIN_LENGTH = 43;

    /**
     * Maximum code verifier length per RFC 7636
     */
    const VERIFIER_MAX_LENGTH = 128;

    /**
     * Valid characters for code verifier (unreserved characters)
     * Per RFC 3986: A-Z a-z 0-9 - . _ ~
     */
    const VERIFIER_CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';

    /**
     * Generate a PKCE code verifier
     * 
     * Generates a cryptographically random string suitable for use as
     * a PKCE code verifier. Should be stored client-side and used to
     * exchange authorization code.
     *
     * @param int $length Length of verifier (43-128, default 128 for security)
     *
     * @return string URL-safe random code verifier
     *
     * @throws TokenException If generation fails
     */
    public function generateCodeVerifier(int $length = self::VERIFIER_MAX_LENGTH): string
    {
        try {
            // Validate length
            if ($length < self::VERIFIER_MIN_LENGTH) {
                throw new TokenException(
                    "Code verifier must be at least " . self::VERIFIER_MIN_LENGTH . " characters"
                );
            }
            if ($length > self::VERIFIER_MAX_LENGTH) {
                throw new TokenException(
                    "Code verifier must not exceed " . self::VERIFIER_MAX_LENGTH . " characters"
                );
            }

            // Generate random bytes
            $randomBytes = random_bytes(ceil($length * 6 / 8));

            // Convert to base64url and trim to exact length
            $encoded = rtrim(strtr(base64_encode($randomBytes), '+/', '-_'), '=');
            $verifier = substr($encoded, 0, $length);

            // Validate characters
            if (!preg_match('/^[A-Za-z0-9\-._~]+$/', $verifier)) {
                throw new TokenException("Generated verifier contains invalid characters");
            }

            return $verifier;
        } catch (TokenException $e) {
            throw $e;
        } catch (\Exception $e) {
            throw new TokenException("Failed to generate code verifier: " . $e->getMessage());
        }
    }

    /**
     * Generate PKCE code challenge from verifier
     * 
     * Creates a code challenge using the specified method:
     * - "S256": SHA256(verifier) base64url encoded (RECOMMENDED)
     * - "plain": verifier as-is (for older clients, less secure)
     *
     * @param string $verifier Code verifier (43-128 chars)
     * @param string $method Challenge method: "S256" or "plain" (default: "S256")
     *
     * @return string Code challenge for authorization request
     *
     * @throws TokenException If challenge generation fails
     */
    public function generateCodeChallenge(string $verifier, string $method = 'S256'): string
    {
        try {
            // Validate verifier
            $this->validateVerifier($verifier);

            if ($method === 'S256') {
                // S256: SHA256(verifier), base64url encoded (RECOMMENDED)
                $hash = hash('sha256', $verifier, true);
                return rtrim(strtr(base64_encode($hash), '+/', '-_'), '=');
            } elseif ($method === 'plain') {
                // Plain: verifier as-is
                return $verifier;
            } else {
                throw new TokenException("Unsupported code challenge method: {$method}");
            }
        } catch (TokenException $e) {
            throw $e;
        } catch (\Exception $e) {
            throw new TokenException("Failed to generate code challenge: " . $e->getMessage());
        }
    }

    /**
     * Validate code challenge matches verifier
     * 
     * Verifies that the provided code_verifier generates the stored
     * code_challenge during token exchange. This proves the client
     * making the request is the same client that initiated the flow.
     *
     * @param string $verifier Code verifier from token request
     * @param string $challenge Stored code challenge from auth code
     * @param string $method Challenge method used: "S256" or "plain"
     *
     * @return bool True if verification succeeds
     *
     * @throws TokenException If verification fails
     */
    public function validateCodeChallenge(
        string $verifier,
        string $challenge,
        string $method = 'S256'
    ): bool
    {
        try {
            // Validate verifier format
            $this->validateVerifier($verifier);

            // Generate expected challenge from verifier
            $expectedChallenge = $this->generateCodeChallenge($verifier, $method);

            // Compare using constant-time comparison to prevent timing attacks
            if (!hash_equals($expectedChallenge, $challenge)) {
                throw new TokenException("Code challenge verification failed");
            }

            return true;
        } catch (TokenException $e) {
            throw $e;
        } catch (\Exception $e) {
            throw new TokenException("Code challenge validation failed: " . $e->getMessage());
        }
    }

    /**
     * Validate code verifier format
     * 
     * Ensures verifier meets RFC 7636 requirements:
     * - Length: 43-128 characters
     * - Characters: unreserved characters only (A-Za-z0-9 - . _ ~)
     *
     * @param string $verifier Code verifier to validate
     *
     * @return bool True if verifier is valid
     *
     * @throws TokenException If verifier is invalid
     */
    public function validateVerifier(string $verifier): bool
    {
        // Check length
        $length = strlen($verifier);
        if ($length < self::VERIFIER_MIN_LENGTH) {
            throw new TokenException(
                "Code verifier too short: {$length} < " . self::VERIFIER_MIN_LENGTH
            );
        }
        if ($length > self::VERIFIER_MAX_LENGTH) {
            throw new TokenException(
                "Code verifier too long: {$length} > " . self::VERIFIER_MAX_LENGTH
            );
        }

        // Check characters (RFC 3986 unreserved: ALPHA / DIGIT / "-" / "." / "_" / "~")
        if (!preg_match('/^[A-Za-z0-9\-._~]+$/', $verifier)) {
            throw new TokenException("Code verifier contains invalid characters");
        }

        return true;
    }

    /**
     * Check if PKCE is required for client
     * 
     * Per RFC 7636 §4.1, PKCE SHOULD be required for public clients:
     * - Native mobile applications
     * - Browser-based single-page applications
     * - Desktop applications
     *
     * @param string $clientType Type of client (public, confidential, etc.)
     *
     * @return bool True if PKCE required for this client type
     */
    public function isPKCERequired(string $clientType = 'public'): bool
    {
        // Public clients MUST use PKCE
        if (strtolower($clientType) === 'public') {
            return true;
        }

        // Confidential clients (backend servers) can skip PKCE
        if (strtolower($clientType) === 'confidential') {
            return false;
        }

        // Default to required for safety
        return true;
    }

    /**
     * Get recommended PKCE parameters for client initialization
     * 
     * Returns recommended values for client applications to use
     * when initiating an authorization request.
     *
     * @return array Recommended PKCE parameters
     */
    public function getRecommendedParameters(): array
    {
        $verifier = $this->generateCodeVerifier(128); // Maximum security
        $challenge = $this->generateCodeChallenge($verifier, 'S256'); // Recommended method

        return [
            'code_verifier' => $verifier,
            'code_challenge' => $challenge,
            'code_challenge_method' => 'S256',
            'verifier_length' => strlen($verifier),
            'challenge_length' => strlen($challenge),
        ];
    }
}
